version: "3.9"

services:
  web:
    build: ./app
    ports:
      - "${FLASK_PORT}:5000"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - backend
      - external-network

  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT}:6379"
    # Volumes is used to persist data across container restarts
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - backend
      - external-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - backend

volumes:
  redis_data:

networks:
  backend:
  # this is a external network called "external-network" -> docker network create external-network
  # se agrega a todos los containers que tendran acceso
  external-network:
    external: true
